### ISSUE TITLE
Task can be completed before file upload is completed

### ISSUE THREAD

**Issue by rickmakkinga** [fi-group/clearly#74] opened 2018-07-25 07:03 UTC
### Description
When executing a process step with a blob attribute, the process step can be completed before the upload process of all files is completed. Only the uploaded files appear in the meta data.

### Screenshots
![image](https://user-images.githubusercontent.com/24542664/43184112-c58d94ac-8fe7-11e8-8d61-b518af56e063.png)

### Steps to reproduce the behavior
1. Execute a process step that includes a 'blob' attribute (file upload).
2. Upload some (large) files.
3. Click the 'save' button before the uploading is completed.

### Expected behavior
One cannot click the 'save' button before the uploading of files is completed (as is the case with comments).

### Actual behavior
The process step can be completed before the uploading is completed.

### Browser affected
- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari
- [x] IE 11

**Comment by smeijer** [comment] 2018-07-27 17:14
This functionality is by design, so you can continue completing other tasks, without waiting for the uploads to finish.

In case you would leave Clearly by either navigating away or closing the browser (tab), you'll receive a warning that there are still pending changes. Press `cancel` there, and the uploads will continue. Press `confirm` and the browser will listen, and navigate away. The uploads are in this case being canceled.

The `uploading x files` message will appear on top of everything, keeping it in the users focus all the time. New files from other tasks are being appended to the upload queue.

Comments do not have this functionality, that's why you need to wait before submitting the form. Because "commenters" are a different kind of users, we currently do not have any plans to implement this functionality on comments either. 

Where it's an awesome power tool while running through tasks, it can be a potential risk in comments.

![image](https://user-images.githubusercontent.com/1196524/43335598-d6aad238-91cf-11e8-8a12-53413e8aec81.png)

**Closed by smeijer** 2018-07-27 17:14 UTC
